### ISSUE TITLE
If creation of a new Connector fails, connect service itself is going down.

### ISSUE THREAD

**Issue by srijiths** [confluentinc/kafka#103]
I have connect service running with one connector say MQTT source. When i register a ES Sink connector , it fails due to some dependencies. But due to that issue the connect interface itself goes down.

**Comment by ewencp** [comment]
@srijiths It sounds like the connector was not installed correctly. Connectors should always include all dependencies that are not already included with connect.

Since this repository is only a mirror and for tagging our own release, I'm going to close this. If you'd like to follow up, please post to our [mailing list](https://groups.google.com/forum/#!forum/confluent-platform).
