### ISSUE TITLE
On the fly creation of connectors ?

### ISSUE THREAD

**Issue by srijiths** [confluentinc/kafka#104]
If i have a connect service running , i am trying to create a new connector say ES Sink. Created a directory under /usr/share/java/kafka-connect-es and copied all the dependent jars. Now i triggered a REST POST call to register this ES Sink. But its failing to get the classes from /usr/share/java/kafka-connect-es.

Does this mean , if i change anything under /usr/share/java/kafka-connect-* it requires a connect service restart ?

**Comment by ewencp** [comment]
@srijiths You'll need to make sure the connector is on the classpath for Connect. You should just be able to set it before running the connect worker, e.g.

```
CLASSPATH=/usr/share/java/kafka-connect-es connect-distributed /etc/schema-registry/connect-avro-distributed.properties
```

We setup the classpath for all our built-in connectors, but since we place each in its own directory, any new connectors need additions to the classpath. We hope to make this process easier in the future.

By the way, we also have a [mailing list](https://groups.google.com/forum/#!forum/confluent-platform) that is probably better for questions like this.
